"""
Vyuha AI — Control Plane Pydantic Models
Shared data models for the Orchestrator, Agent, and API contracts.
"""

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


# --- Enums ---

class NodeState(str, Enum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    HIGH_LATENCY = "HIGH_LATENCY"
    FLAKY = "FLAKY"
    DEAD = "DEAD"
    UNKNOWN = "UNKNOWN"


class IncidentSeverity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class IncidentStatus(str, Enum):
    DETECTED = "detected"
    TRIAGING = "triaging"
    PROPOSED = "proposed"
    APPROVED = "approved"
    REJECTED = "rejected"
    APPLIED = "applied"
    REFLECTED = "reflected"


class FormationAction(str, Enum):
    REROUTE = "reroute"
    DEACTIVATE_NODE = "deactivate_node"
    REACTIVATE_NODE = "reactivate_node"
    REBALANCE = "rebalance"


# --- Node Health ---

class NodeHealthSnapshot(BaseModel):
    node_name: str
    url: str
    state: NodeState
    response_time_ms: float | None = None
    error: str | None = None
    checked_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


# --- Incidents ---

class Incident(BaseModel):
    id: int | None = None
    node_name: str
    severity: IncidentSeverity
    status: IncidentStatus = IncidentStatus.DETECTED
    description: str
    detected_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    resolved_at: str | None = None


# --- Agent Proposals ---

class FormationChange(BaseModel):
    """A proposed change to the routing formation, generated by the GLM agent."""
    incident_id: int
    action: FormationAction
    target_node: str
    reasoning: str
    proposed_config: dict
    remediation_action: str | None = None
    confidence: float = Field(ge=0.0, le=1.0)


class AgentProposal(BaseModel):
    id: int | None = None
    incident_id: int
    formation_change: FormationChange
    agent_reasoning: str
    status: IncidentStatus = IncidentStatus.PROPOSED
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


# --- Human Feedback ---

class ApprovalRequest(BaseModel):
    proposal_id: int
    feedback: str = ""


class RejectionRequest(BaseModel):
    proposal_id: int
    feedback: str


# --- Evolutionary Memory ---

class Learning(BaseModel):
    id: int | None = None
    incident_id: int
    proposal_id: int
    was_approved: bool
    human_feedback: str
    agent_reflection: str
    lesson_learned: str
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


# --- API Responses ---

class MonitorStatusResponse(BaseModel):
    orchestrator_uptime: float
    monitoring_active: bool
    node_states: list[NodeHealthSnapshot]
    active_incidents: list[Incident]
    pending_proposals: list[AgentProposal]
    circuit_breaker_active: bool
    consecutive_agent_failures: int


class IncidentDetailResponse(BaseModel):
    incident: Incident
    proposals: list[AgentProposal]
    learnings: list[Learning]
